project_id = "xvtmrnmwmuroksneekbl"

[functions.delete-collection]
verify_jwt = true

[functions.delete-election]
verify_jwt = true

[functions.delete-profile]
verify_jwt = true

[functions.import-image-from-url]
verify_jwt = false

[functions.import-images-batch]
verify_jwt = false

[functions.import-lifeline-cover-image]
verify_jwt = false

[functions.find-and-import-lifeline-images]
verify_jwt = false

[functions.upload-profiles]
verify_jwt = false

[functions.upload-profile-works]
verify_jwt = false

[functions.upload-profile-relationships]
verify_jwt = false

[functions.export-lifeline-data]
verify_jwt = false

[functions.export-collection-data]
verify_jwt = false